//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "ABFormat", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (ABFormat.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a ABFormat-test.ck boilerplate ChucK program
//      to help test your chugin (see ABFormat-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "chugin.h"
#include "ABFormat.h"

// general includes
#include <iostream>


// declaration of chugin constructor
CK_DLL_CTOR( abformat_ctor );
// declaration of chugin desctructor
CK_DLL_DTOR( abformat_dtor );

// for chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICKF( abformat_tickf );

// this is a special offset reserved for chugin internal data
t_CKINT abformat_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( ABFormat )
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "v1.0.0" );
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "Everett M. Carpenter" );
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "A first order A-BFormat converter" );
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "https://github.com/everettmcarpenter/Encode-Decode.chug/tree/32486a2a3fcbb03b66f6b0c5dfaeed064a58e200/B-A-BFormat.chug/ABFormat.chug" );
    // (optional) contact email
    QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "carpee2[at]rpi[dot]edu" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( ABFormat )
{
    // generally, don't change this...
    QUERY->setname( QUERY, "ABFormat" );
    QUERY->doc_class(QUERY, "A class for converting A-Format ambisonics signals to B-Format ambisonic signals.");
    QUERY->begin_class( QUERY, "ABFormat", "UGen" );
    QUERY->add_ctor( QUERY, abformat_ctor );
    QUERY->add_dtor( QUERY, abformat_dtor );
    QUERY->add_ugen_funcf( QUERY, abformat_tickf, NULL, 4, 4 );;
    abformat_data_offset = QUERY->add_mvar( QUERY, "int", "@abf_data", false );

    // ------------------------------------------------------------------------
    // end the class definition
    // IMPORTANT: this MUST be called to each class definition!
    // ------------------------------------------------------------------------
    QUERY->end_class( QUERY );

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( abformat_ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, abformat_data_offset ) = 0;
    
    // instantiate our internal c++ class representation
    ABFormat1 * abf_obj = new ABFormat1( API->vm->srate(VM) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, abformat_data_offset ) = (t_CKINT)abf_obj;
}


// implementation for the destructor
CK_DLL_DTOR( abformat_dtor )
{
    // get our c++ class pointer
    ABFormat1 * abf_obj = (ABFormat1 *)OBJ_MEMBER_INT( SELF, abformat_data_offset );
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE( abf_obj );
    // set the data field to 0
    OBJ_MEMBER_INT( SELF, abformat_data_offset ) = 0;
}


// implementation for tick function (relevant only for UGens)
CK_DLL_TICKF( abformat_tickf )
{
    // get our c++ class pointer
    ABFormat1 * abf_obj = (ABFormat1 *)OBJ_MEMBER_INT(SELF, abformat_data_offset);
 
    // invoke our tick function; store in the magical out variable
    if( abf_obj )abf_obj->tick( in, out, nframes );

    // yes
    return TRUE;
}
