//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "MonoDecode", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (MonoDecode.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a MonoDecode-test.ck boilerplate ChucK program
//      to help test your chugin (see MonoDecode-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "chugin.h"
#include "MonoDecode.h"

// general includes
#include <iostream>

// DECODE1 function defs
CK_DLL_CTOR(decode1_ctor);
CK_DLL_DTOR(decode1_dtor);
CK_DLL_MFUN(decode1_setSH);
CK_DLL_MFUN(decode1_getSH);
CK_DLL_MFUN(decode1_getRMS);
CK_DLL_TICKF(decode1_tickf);
CK_DLL_MFUN(decode1_setWeights);
CK_DLL_MFUN(decode1_getWeights);

// this is a special offset reserved for chugin internal data
t_CKINT decode1_data_offset = 0;

// DECODE2 function defs
CK_DLL_CTOR(decode2_ctor);
CK_DLL_DTOR(decode2_dtor);
CK_DLL_MFUN(decode2_setSH);
CK_DLL_MFUN(decode2_getSH);
CK_DLL_MFUN(decode2_getRMS);
CK_DLL_TICKF(decode2_tickf);
CK_DLL_MFUN(decode2_setWeights);
CK_DLL_MFUN(decode2_getWeights);

// this is a special offset reserved for chugin internal data
t_CKINT decode2_data_offset = 0;

// DECODE3 function defs
CK_DLL_CTOR(decode3_ctor);
CK_DLL_DTOR(decode3_dtor);
CK_DLL_MFUN(decode3_setSH);
CK_DLL_MFUN(decode3_getSH);
CK_DLL_MFUN(decode3_getRMS);
CK_DLL_TICKF(decode3_tickf);
CK_DLL_MFUN(decode3_setWeights);
CK_DLL_MFUN(decode3_getWeights);

// this is a special offset reserved for chugin internal data
t_CKINT decode3_data_offset = 0;

// DECODE4 function defs
CK_DLL_CTOR(decode4_ctor);
CK_DLL_DTOR(decode4_dtor);
CK_DLL_MFUN(decode4_setSH);
CK_DLL_MFUN(decode4_getSH);
CK_DLL_MFUN(decode4_getRMS);
CK_DLL_TICKF(decode4_tickf);
CK_DLL_MFUN(decode4_setWeights);
CK_DLL_MFUN(decode4_getWeights);

// this is a special offset reserved for chugin internal data
t_CKINT decode4_data_offset = 0;

// DECODE5 function defs
CK_DLL_CTOR(decode5_ctor);
CK_DLL_DTOR(decode5_dtor);
CK_DLL_MFUN(decode5_setSH);
CK_DLL_MFUN(decode5_getSH);
CK_DLL_MFUN(decode5_getRMS);
CK_DLL_TICKF(decode5_tickf);
CK_DLL_MFUN(decode5_setWeights);
CK_DLL_MFUN(decode5_getWeights);
// this is a special offset reserved for chugin internal data
t_CKINT decode5_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO(MonoDecode)
{
    // the version string of this chugin, e.g., "v1.2.2"
    QUERY->setinfo(QUERY, CHUGIN_INFO_CHUGIN_VERSION, "v1.2.2");
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo(QUERY, CHUGIN_INFO_AUTHORS, "Everett M. Carpenter");
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo(QUERY, CHUGIN_INFO_DESCRIPTION, "A customizable mono decoder, expects direct spherical harmonics");
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo(QUERY, CHUGIN_INFO_URL, "https://github.com/SaintEverett/Encode-MonoDecode.chug/tree/32486a2a3fcbb03b66f6b0c5dfaeed064a58e200/Decode.chug/MonoDecodeN");
    // (optional) contact email
    QUERY->setinfo(QUERY, CHUGIN_INFO_EMAIL, "carpee2[at]rpi[dot]edu");
}

//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY(MonoDecode)
{
    // generally, don't change this...
    QUERY->setname(QUERY, "MonoDecode");
    QUERY->begin_class(QUERY, "MonoDecode1", "UGen");
    QUERY->doc_class(QUERY, "MonoDecoder based on a given vector of spherical harmonic values.");
    QUERY->add_ctor(QUERY, decode1_ctor);
    QUERY->add_dtor(QUERY, decode1_dtor);
    QUERY->add_ugen_funcf(QUERY, decode1_tickf, NULL, 4, 1);
    QUERY->add_mfun(QUERY, decode1_setSH, "void", "sh");
    QUERY->add_arg(QUERY, "float[]", "sh");
    QUERY->doc_func(QUERY, "A simple sampling decoder used to find metrics of a soundfield. It's processing is similar to the inverse of encoding, where it will find sound present at a position on the sphere, rather than place it at that position.");
    QUERY->add_mfun(QUERY, decode1_getSH, "float[]", "sh");
    QUERY->doc_func(QUERY, "Get current vector of spherical harmonics.");
    QUERY->add_mfun(QUERY, decode1_getRMS, "float", "rms");
    QUERY->doc_func(QUERY, "Get the RMS value of the last buffer pass.");
    QUERY->add_mfun(QUERY, decode1_setWeights, "void", "weights");
    QUERY->add_arg(QUERY, "float[]", "weights");
    QUERY->doc_func(QUERY, "Set vector of weights to be used, the same vector is used for all speakers.");
    QUERY->add_mfun(QUERY, decode1_getWeights, "float[]", "weights");
    QUERY->doc_func(QUERY, "Get the active weighting of the decoder vector.");
    // this reserves a variable in the ChucK internal class to store
    decode1_data_offset = QUERY->add_mvar(QUERY, "int", "@decode1_data", false);
    QUERY->end_class(QUERY);

    // generally, don't change this...
    QUERY->begin_class(QUERY, "MonoDecode2", "UGen");
    QUERY->doc_class(QUERY, "MonoDecoder based on a given vector of spherical harmonic values.");
    QUERY->add_ctor(QUERY, decode2_ctor);
    QUERY->add_dtor(QUERY, decode2_dtor);
    QUERY->add_ugen_funcf(QUERY, decode2_tickf, NULL, 9, 1);
    QUERY->add_mfun(QUERY, decode2_setSH, "void", "sh");
    QUERY->add_arg(QUERY, "float[]", "sh");
    QUERY->doc_func(QUERY, "A simple sampling decoder used to find metrics of a soundfield. It's processing is similar to the inverse of encoding, where it will find sound present at a position on the sphere, rather than place it at that position.");
    QUERY->add_mfun(QUERY, decode2_getSH, "float[]", "sh");
    QUERY->doc_func(QUERY, "Get current vector of spherical harmonics.");
    QUERY->add_mfun(QUERY, decode2_getRMS, "float", "rms");
    QUERY->doc_func(QUERY, "Get the RMS value of the last buffer pass.");
    QUERY->add_mfun(QUERY, decode2_setWeights, "void", "weights");
    QUERY->add_arg(QUERY, "float[]", "weights");
    QUERY->doc_func(QUERY, "Set vector of weights to be used, the same vector is used for all speakers.");
    QUERY->add_mfun(QUERY, decode2_getWeights, "float[]", "weights");
    QUERY->doc_func(QUERY, "Get the active weighting of the decoder vector.");
    // this reserves a variable in the ChucK internal class to store
    decode2_data_offset = QUERY->add_mvar(QUERY, "int", "@decode2_data", false);
    QUERY->end_class(QUERY);

    // generally, don't change this...
    QUERY->begin_class(QUERY, "MonoDecode3", "UGen");
    QUERY->add_ctor(QUERY, decode3_ctor);
    QUERY->add_dtor(QUERY, decode3_dtor);
    QUERY->add_ugen_funcf(QUERY, decode3_tickf, NULL, 16, 1);
    QUERY->add_mfun(QUERY, decode3_setSH, "void", "sh");
    QUERY->add_arg(QUERY, "float[]", "sh");
    QUERY->doc_func(QUERY, "A simple sampling decoder used to find metrics of a soundfield. It's processing is similar to the inverse of encoding, where it will find sound present at a position on the sphere, rather than place it at that position.");
    QUERY->add_mfun(QUERY, decode3_getSH, "float[]", "sh");
    QUERY->doc_func(QUERY, "Get current vector of spherical harmonics.");
    QUERY->add_mfun(QUERY, decode3_getRMS, "float", "rms");
    QUERY->doc_func(QUERY, "Get the RMS value of the last buffer pass.");
    QUERY->add_mfun(QUERY, decode3_setWeights, "void", "weights");
    QUERY->add_arg(QUERY, "float[]", "weights");
    QUERY->doc_func(QUERY, "Set vector of weights to be used, the same vector is used for all speakers.");
    QUERY->add_mfun(QUERY, decode3_getWeights, "float[]", "weights");
    QUERY->doc_func(QUERY, "Get the active weighting of the decoder vector.");
    // this reserves a variable in the ChucK internal class to store
    decode3_data_offset = QUERY->add_mvar(QUERY, "int", "@decode3_data", false);
    QUERY->end_class(QUERY);

    // generally, don't change this...
    QUERY->begin_class(QUERY, "MonoDecode4", "UGen");
    QUERY->add_ctor(QUERY, decode4_ctor);
    QUERY->add_dtor(QUERY, decode4_dtor);
    QUERY->add_ugen_funcf(QUERY, decode4_tickf, NULL, 25, 1);
    QUERY->add_mfun(QUERY, decode4_setSH, "void", "sh");
    QUERY->add_arg(QUERY, "float[]", "sh");
    QUERY->doc_func(QUERY, "A simple sampling decoder used to find metrics of a soundfield. It's processing is similar to the inverse of encoding, where it will find sound present at a position on the sphere, rather than place it at that position.");
    QUERY->add_mfun(QUERY, decode4_getSH, "float[]", "sh");
    QUERY->doc_func(QUERY, "Get current vector of spherical harmonics.");
    QUERY->add_mfun(QUERY, decode4_getRMS, "float", "rms");
    QUERY->doc_func(QUERY, "Get the RMS value of the last buffer pass.");
    QUERY->add_mfun(QUERY, decode4_setWeights, "void", "weights");
    QUERY->add_arg(QUERY, "float[]", "weights");
    QUERY->doc_func(QUERY, "Set vector of weights to be used, the same vector is used for all speakers.");
    QUERY->add_mfun(QUERY, decode4_getWeights, "float[]", "weights");
    QUERY->doc_func(QUERY, "Get the active weighting of the decoder vector.");
    // this reserves a variable in the ChucK internal class to store
    decode4_data_offset = QUERY->add_mvar(QUERY, "int", "@decode4_data", false);
    QUERY->end_class(QUERY);

    // generally, don't change this...
    QUERY->begin_class(QUERY, "MonoDecode5", "UGen");
    QUERY->add_ctor(QUERY, decode5_ctor);
    QUERY->add_dtor(QUERY, decode5_dtor);
    QUERY->add_ugen_funcf(QUERY, decode5_tickf, NULL, 36, 1);
    QUERY->add_mfun(QUERY, decode5_setSH, "void", "sh");
    QUERY->add_arg(QUERY, "float[]", "sh");
    QUERY->doc_func(QUERY, "A simple sampling decoder used to find metrics of a soundfield. It's processing is similar to the inverse of encoding, where it will find sound present at a position on the sphere, rather than place it at that position.");
    QUERY->add_mfun(QUERY, decode5_getSH, "float[]", "sh");
    QUERY->doc_func(QUERY, "Get current vector of spherical harmonics.");
    QUERY->add_mfun(QUERY, decode5_getRMS, "float", "rms");
    QUERY->doc_func(QUERY, "Get the RMS value of the last buffer pass.");
    QUERY->add_mfun(QUERY, decode5_setWeights, "void", "weights");
    QUERY->add_arg(QUERY, "float[]", "weights");
    QUERY->doc_func(QUERY, "Set vector of weights to be used, the same vector is used for all speakers.");
    QUERY->add_mfun(QUERY, decode5_getWeights, "float[]", "weights");
    QUERY->doc_func(QUERY, "Get the active weighting of the decoder vector.");
    // this reserves a variable in the ChucK internal class to store
    decode5_data_offset = QUERY->add_mvar(QUERY, "int", "@decode5_data", false);
    QUERY->end_class(QUERY);

    //=======================================================================
    // MonoDecodeN (purely for documentation purposes)
    //
    //=======================================================================
    QUERY->begin_class(QUERY, "MonoDecodeN", "UGen");
    QUERY->doc_class(QUERY, "MonoDecoder based on a given vector of spherical harmonic values.");
    QUERY->add_ex(QUERY, "examples/deep/advanced-decode.ck");
    QUERY->add_ctor(QUERY, decode1_ctor);
    QUERY->add_dtor(QUERY, decode1_dtor);
    QUERY->add_ugen_funcf(QUERY, decode1_tickf, NULL, 4, 1);
    QUERY->add_mfun(QUERY, decode1_setSH, "void", "sh");
    QUERY->add_arg(QUERY, "float[]", "sh");
    QUERY->doc_func(QUERY, "A simple sampling decoder used to find metrics of a soundfield. It's processing is similar to the inverse of encoding, where it will find sound present at a position on the sphere, rather than place it at that position.");
    QUERY->add_mfun(QUERY, decode1_getSH, "float[]", "sh");
    QUERY->doc_func(QUERY, "Get current vector of spherical harmonics.");
    QUERY->add_mfun(QUERY, decode1_getRMS, "float", "rms");
    QUERY->doc_func(QUERY, "Get the RMS value of the last buffer pass.");
    QUERY->add_mfun(QUERY, decode1_setWeights, "void", "weights");
    QUERY->add_arg(QUERY, "float[]", "weights");
    QUERY->doc_func(QUERY, "Set vector of weights to be used, the same vector is used for all speakers.");
    QUERY->add_mfun(QUERY, decode1_getWeights, "float[]", "weights");
    QUERY->doc_func(QUERY, "Get the active weighting of the decoder vector.");
    // this reserves a variable in the ChucK internal class to store
    decode1_data_offset = QUERY->add_mvar(QUERY, "int", "@decode1_data", false);
    QUERY->end_class(QUERY);

    // wasn't that a breeze?
    return TRUE;
}

//=================================================//
// ************************************************//
//                                                 //
// MonoDecode1 DLL definitions ; Everett M. Carpenter  //
//                                                 //
// ************************************************//
//=================================================//
// implementation for the default constructor

// implementation for the default constructor
CK_DLL_CTOR(decode1_ctor)
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT(SELF, decode1_data_offset) = 0;
    // instantiate our internal c++ class representation
    MonoDecode1 *decode1_obj = new MonoDecode1(API->vm->srate(VM));
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT(SELF, decode1_data_offset) = (t_CKINT)decode1_obj;
}

// implementation for the destructor
CK_DLL_DTOR(decode1_dtor)
{
    // get our c++ class pointer
    MonoDecode1 *decode1_obj = (MonoDecode1 *)OBJ_MEMBER_INT(SELF, decode1_data_offset);
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE(decode1_obj);
    // set the data field to 0
    OBJ_MEMBER_INT(SELF, decode1_data_offset) = 0;
}

// implementation for tick function (relevant only for UGens)
CK_DLL_TICKF(decode1_tickf)
{
    // get our c++ class pointer
    MonoDecode1 *decode1_obj = (MonoDecode1 *)OBJ_MEMBER_INT(SELF, decode1_data_offset);
    if (decode1_obj)
        decode1_obj->tick(in, out, nframes);
    // yes
    return TRUE;
}

CK_DLL_MFUN(decode1_setSH)
{
    Chuck_ArrayFloat* weights = (Chuck_ArrayFloat*)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode1* decode1_obj = (MonoDecode1*)OBJ_MEMBER_INT(SELF, decode1_data_offset);
    if (decode1_obj)
        decode1_obj->CKsetSpeakSH(weights, API);
}

CK_DLL_MFUN(decode1_getSH)
{
    // get our c++ class pointer
    MonoDecode1* decode1_obj = (MonoDecode1*)OBJ_MEMBER_INT(SELF, decode1_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (t_CKINT i = 0; i < decode1_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode1_obj->mySH[i]);
    }
    // set return value
    RETURN->v_object = (Chuck_Object*)coordinatearray;
}

CK_DLL_MFUN(decode1_getRMS)
{
    // get our c++ class pointer
    MonoDecode1* decode1_obj = (MonoDecode1*)OBJ_MEMBER_INT(SELF, decode1_data_offset);
    RETURN->v_float = decode1_obj->rms;
}

CK_DLL_MFUN(decode1_setWeights)
{
    Chuck_ArrayFloat *weights = (Chuck_ArrayFloat *)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode1 *decode1_obj = (MonoDecode1 *)OBJ_MEMBER_INT(SELF, decode1_data_offset);
    if (decode1_obj)
        decode1_obj->CKsetWeights(weights, API);
}

CK_DLL_MFUN(decode1_getWeights)
{
    // get our c++ class pointer
    MonoDecode1* decode1_obj = (MonoDecode1*)OBJ_MEMBER_INT(SELF, decode1_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (int i = 0; i < decode1_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode1_obj->weights[i]);
    }

    RETURN->v_object = (Chuck_Object*)coordinatearray;
}

//=================================================//
// ************************************************//
//                                                 //
// MonoDecode2 DLL definitions ; Everett M. Carpenter  //
//                                                 //
// ************************************************//
//=================================================//
// implementation for the default constructor

// implementation for the default constructor
CK_DLL_CTOR(decode2_ctor)
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT(SELF, decode2_data_offset) = 0;
    // instantiate our internal c++ class representation
    MonoDecode2 *decode2_obj = new MonoDecode2(API->vm->srate(VM));
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT(SELF, decode2_data_offset) = (t_CKINT)decode2_obj;
}

// implementation for the destructor
CK_DLL_DTOR(decode2_dtor)
{
    // get our c++ class pointer
    MonoDecode2 *decode2_obj = (MonoDecode2 *)OBJ_MEMBER_INT(SELF, decode2_data_offset);
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE(decode2_obj);
    // set the data field to 0
    OBJ_MEMBER_INT(SELF, decode2_data_offset) = 0;
}

// implementation for tick function (relevant only for UGens)
CK_DLL_TICKF(decode2_tickf)
{
    // get our c++ class pointer
    MonoDecode2 *decode2_obj = (MonoDecode2 *)OBJ_MEMBER_INT(SELF, decode2_data_offset);
    if (decode2_obj)
        decode2_obj->tick(in, out, nframes);
    // yes
    return TRUE;
}

CK_DLL_MFUN(decode2_setSH)
{
    Chuck_ArrayFloat* weights = (Chuck_ArrayFloat*)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode2* decode2_obj = (MonoDecode2*)OBJ_MEMBER_INT(SELF, decode2_data_offset);
    if (decode2_obj)
        decode2_obj->CKsetSpeakSH(weights, API);
}

CK_DLL_MFUN(decode2_getSH)
{
    // get our c++ class pointer
    MonoDecode2* decode2_obj = (MonoDecode2*)OBJ_MEMBER_INT(SELF, decode2_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (t_CKINT i = 0; i < decode2_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode2_obj->mySH[i]);
    }
    // set return value
    RETURN->v_object = (Chuck_Object*)coordinatearray;
}

CK_DLL_MFUN(decode2_getRMS)
{
    // get our c++ class pointer
    MonoDecode2* decode2_obj = (MonoDecode2*)OBJ_MEMBER_INT(SELF, decode2_data_offset);
    RETURN->v_float = decode2_obj->rms;
}

CK_DLL_MFUN(decode2_setWeights)
{
    Chuck_ArrayFloat *weights = (Chuck_ArrayFloat *)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode2 *decode2_obj = (MonoDecode2 *)OBJ_MEMBER_INT(SELF, decode2_data_offset);
    if (decode2_obj)
        decode2_obj->CKsetWeights(weights, API);
}

CK_DLL_MFUN(decode2_getWeights)
{
    // get our c++ class pointer
    MonoDecode2* decode2_obj = (MonoDecode2*)OBJ_MEMBER_INT(SELF, decode2_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (int i = 0; i < decode2_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode2_obj->weights[i]);
    }

    RETURN->v_object = (Chuck_Object*)coordinatearray;
}

//=================================================//
// ************************************************//
//                                                 //
// MonoDecode3 DLL definitions ; Everett M. Carpenter  //
//                                                 //
// ************************************************//
//=================================================//
// implementation for the default constructor

// implementation for the default constructor
CK_DLL_CTOR(decode3_ctor)
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT(SELF, decode3_data_offset) = 0;
    // instantiate our internal c++ class representation
    MonoDecode3 *decode3_obj = new MonoDecode3(API->vm->srate(VM));
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT(SELF, decode3_data_offset) = (t_CKINT)decode3_obj;
}

// implementation for the destructor
CK_DLL_DTOR(decode3_dtor)
{
    // get our c++ class pointer
    MonoDecode3 *decode3_obj = (MonoDecode3 *)OBJ_MEMBER_INT(SELF, decode3_data_offset);
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE(decode3_obj);
    // set the data field to 0
    OBJ_MEMBER_INT(SELF, decode3_data_offset) = 0;
}

// implementation for tick function (relevant only for UGens)
CK_DLL_TICKF(decode3_tickf)
{
    // get our c++ class pointer
    MonoDecode3 *decode3_obj = (MonoDecode3 *)OBJ_MEMBER_INT(SELF, decode3_data_offset);
    if (decode3_obj)
        decode3_obj->tick(in, out, nframes);
    // yes
    return TRUE;
}

CK_DLL_MFUN(decode3_setSH)
{
    Chuck_ArrayFloat* weights = (Chuck_ArrayFloat*)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode3* decode3_obj = (MonoDecode3*)OBJ_MEMBER_INT(SELF, decode3_data_offset);
    if (decode3_obj)
        decode3_obj->CKsetSpeakSH(weights, API);
}

CK_DLL_MFUN(decode3_getSH)
{
    // get our c++ class pointer
    MonoDecode3* decode3_obj = (MonoDecode3*)OBJ_MEMBER_INT(SELF, decode3_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (t_CKINT i = 0; i < decode3_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode3_obj->mySH[i]);
    }
    // set return value
    RETURN->v_object = (Chuck_Object*)coordinatearray;
}

CK_DLL_MFUN(decode3_getRMS)
{
    // get our c++ class pointer
    MonoDecode3* decode3_obj = (MonoDecode3*)OBJ_MEMBER_INT(SELF, decode3_data_offset);
    RETURN->v_float = decode3_obj->rms;
}

CK_DLL_MFUN(decode3_setWeights)
{
    Chuck_ArrayFloat *weights = (Chuck_ArrayFloat *)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode3 *decode3_obj = (MonoDecode3 *)OBJ_MEMBER_INT(SELF, decode3_data_offset);
    if (decode3_obj)
        decode3_obj->CKsetWeights(weights, API);
}

CK_DLL_MFUN(decode3_getWeights)
{
    // get our c++ class pointer
    MonoDecode3* decode3_obj = (MonoDecode3*)OBJ_MEMBER_INT(SELF, decode3_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (int i = 0; i < decode3_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode3_obj->weights[i]);
    }

    RETURN->v_object = (Chuck_Object*)coordinatearray;
}

//=================================================//
// ************************************************//
//                                                 //
// MonoDecode4 DLL definitions ; Everett M. Carpenter  //
//                                                 //
// ************************************************//
//=================================================//
// implementation for the default constructor

// implementation for the default constructor
CK_DLL_CTOR(decode4_ctor)
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT(SELF, decode4_data_offset) = 0;
    // instantiate our internal c++ class representation
    MonoDecode4 *decode4_obj = new MonoDecode4(API->vm->srate(VM));
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT(SELF, decode4_data_offset) = (t_CKINT)decode4_obj;
}

// implementation for the destructor
CK_DLL_DTOR(decode4_dtor)
{
    // get our c++ class pointer
    MonoDecode4 *decode4_obj = (MonoDecode4 *)OBJ_MEMBER_INT(SELF, decode4_data_offset);
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE(decode4_obj);
    // set the data field to 0
    OBJ_MEMBER_INT(SELF, decode4_data_offset) = 0;
}

// implementation for tick function (relevant only for UGens)
CK_DLL_TICKF(decode4_tickf)
{
    // get our c++ class pointer
    MonoDecode4 *decode4_obj = (MonoDecode4 *)OBJ_MEMBER_INT(SELF, decode4_data_offset);
    if (decode4_obj)
        decode4_obj->tick(in, out, nframes);
    // yes
    return TRUE;
}

CK_DLL_MFUN(decode4_setSH)
{
    Chuck_ArrayFloat* weights = (Chuck_ArrayFloat*)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode4* decode4_obj = (MonoDecode4*)OBJ_MEMBER_INT(SELF, decode4_data_offset);
    if (decode4_obj)
        decode4_obj->CKsetSpeakSH(weights, API);
}

CK_DLL_MFUN(decode4_getSH)
{
    // get our c++ class pointer
    MonoDecode4* decode4_obj = (MonoDecode4*)OBJ_MEMBER_INT(SELF, decode4_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (t_CKINT i = 0; i < decode4_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode4_obj->mySH[i]);
    }
    // set return value
    RETURN->v_object = (Chuck_Object*)coordinatearray;
}

CK_DLL_MFUN(decode4_getRMS)
{
    // get our c++ class pointer
    MonoDecode4* decode4_obj = (MonoDecode4*)OBJ_MEMBER_INT(SELF, decode4_data_offset);
    RETURN->v_float = decode4_obj->rms;
}

CK_DLL_MFUN(decode4_setWeights)
{
    Chuck_ArrayFloat *weights = (Chuck_ArrayFloat *)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode4 *decode4_obj = (MonoDecode4 *)OBJ_MEMBER_INT(SELF, decode4_data_offset);
    if (decode4_obj)
        decode4_obj->CKsetWeights(weights, API);
}

CK_DLL_MFUN(decode4_getWeights)
{
    // get our c++ class pointer
    MonoDecode4* decode4_obj = (MonoDecode4*)OBJ_MEMBER_INT(SELF, decode4_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (int i = 0; i < decode4_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode4_obj->weights[i]);
    }

    RETURN->v_object = (Chuck_Object*)coordinatearray;
}

//=================================================//
// ************************************************//
//                                                 //
// MonoDecode5 DLL definitions ; Everett M. Carpenter  //
//                                                 //
// ************************************************//
//=================================================//
// implementation for the default constructor

// implementation for the default constructor
CK_DLL_CTOR(decode5_ctor)
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT(SELF, decode5_data_offset) = 0;
    // instantiate our internal c++ class representation
    MonoDecode5 *decode5_obj = new MonoDecode5(API->vm->srate(VM));
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT(SELF, decode5_data_offset) = (t_CKINT)decode5_obj;
}

// implementation for the destructor
CK_DLL_DTOR(decode5_dtor)
{
    // get our c++ class pointer
    MonoDecode5 *decode5_obj = (MonoDecode5 *)OBJ_MEMBER_INT(SELF, decode5_data_offset);
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE(decode5_obj);
    // set the data field to 0
    OBJ_MEMBER_INT(SELF, decode5_data_offset) = 0;
}

// implementation for tick function (relevant only for UGens)
CK_DLL_TICKF(decode5_tickf)
{
    // get our c++ class pointer
    MonoDecode5 *decode5_obj = (MonoDecode5 *)OBJ_MEMBER_INT(SELF, decode5_data_offset);
    if (decode5_obj)
        decode5_obj->tick(in, out, nframes);
    // yes
    return TRUE;
}

CK_DLL_MFUN(decode5_setSH)
{
    Chuck_ArrayFloat* weights = (Chuck_ArrayFloat*)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode5* decode5_obj = (MonoDecode5*)OBJ_MEMBER_INT(SELF, decode5_data_offset);
    if (decode5_obj)
        decode5_obj->CKsetSpeakSH(weights, API);
}

CK_DLL_MFUN(decode5_getSH)
{
    // get our c++ class pointer
    MonoDecode5* decode5_obj = (MonoDecode5*)OBJ_MEMBER_INT(SELF, decode5_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (t_CKINT i = 0; i < decode5_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode5_obj->mySH[i]);
    }
    // set return value
    RETURN->v_object = (Chuck_Object*)coordinatearray;
}

CK_DLL_MFUN(decode5_getRMS)
{
    // get our c++ class pointer
    MonoDecode5* decode5_obj = (MonoDecode5*)OBJ_MEMBER_INT(SELF, decode5_data_offset);
    RETURN->v_float = decode5_obj->rms;
}

CK_DLL_MFUN(decode5_setWeights)
{
    Chuck_ArrayFloat *weights = (Chuck_ArrayFloat *)GET_NEXT_OBJECT(ARGS);
    // get our c++ class pointer
    MonoDecode5 *decode5_obj = (MonoDecode5 *)OBJ_MEMBER_INT(SELF, decode5_data_offset);
    if (decode5_obj)
        decode5_obj->CKsetWeights(weights, API);
}

CK_DLL_MFUN(decode5_getWeights)
{
    // get our c++ class pointer
    MonoDecode5* decode5_obj = (MonoDecode5*)OBJ_MEMBER_INT(SELF, decode5_data_offset);

    // Create a float[] array
    Chuck_DL_Api::Object returnarray = API->object->create(SHRED, API->type->lookup(VM, "float[]"), false);
    Chuck_ArrayFloat* coordinatearray = (Chuck_ArrayFloat*)returnarray;
    for (int i = 0; i < decode5_obj->n_channels; i++)
    {
        API->object->array_float_push_back(coordinatearray, decode5_obj->weights[i]);
    }

    RETURN->v_object = (Chuck_Object*)coordinatearray;
}