//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------
// NOTE by default, chuginate generates a new UGen subclass in this file
//      but it is possible, of course, to create non-UGen classes in a chugin!
// To modify this generated file for a non-UGen class...
//      1. in QUERY->begin_class(), change "UGen" to a different ChucK class
//         (e.g., `QUERY->begin_class(QUERY, "AmbiCorder", "Object");`)
//      2. remove or commment out the line containing QUERY->add_ugen_func()
//      3. that's it; the rest is no different for UGens/non-UGens
//-----------------------------------------------------------------------------
// NOTE once you have built this into a chugin (AmbiCorder.chug), here are a few
//      helpful tools for testing / probing / verifying your new chugin!
//
// chuginate also generated a AmbiCorder-test.ck boilerplate ChucK program
//      to help test your chugin (see AmbiCorder-test.ck for more instructions)
//
// run `chuck --chugin-probe` to probe what chugins would be loaded, and
//      from where in the chugin search paths
//
// run `chuck -v3 --loop` to see what chugins are actually loaded at runtime,
//      with more info and error reporting than with --chugin-probe
//
// other helpful chugin-related flags include:
//      --chugin:<filename>
//      --chugin-path:(path) / -G(path)
//      --chugin-load:{on/off}
//
// for more information on command-line options:
//      https://chuck.stanford.edu/doc/program/options.html
// for more information on chugins:
//      https://chuck.stanford.edu/extend/
//-----------------------------------------------------------------------------
// happy chucking & chugging!
//-----------------------------------------------------------------------------

// include chugin header
#include "chugin.h"
#include "AmbiCorder.h"

// general includes
#include <iostream>

CK_DLL_CTOR( ambicorder1_ctor );
CK_DLL_DTOR( ambicorder1_dtor );
CK_DLL_MFUN( ambicorder1_openFile );
CK_DLL_MFUN( ambicorder1_closeFile );
CK_DLL_TICKF( ambicorder1_tick );
t_CKINT ambicorder1_data_offset = 0;

CK_DLL_CTOR(ambicorder2_ctor);
CK_DLL_DTOR(ambicorder2_dtor);
CK_DLL_MFUN(ambicorder2_setParam);
CK_DLL_MFUN(ambicorder2_getParam);
CK_DLL_TICKF(ambicorder2_tick);
t_CKINT ambicorder2_data_offset = 0;

//-----------------------------------------------------------------------------
// info function: ChucK calls this when loading/probing the chugin
// NOTE: please customize these info fields below; they will be used for
// chugins loading, probing, and package management and documentation
//-----------------------------------------------------------------------------
CK_DLL_INFO( AmbiCorder )
{
    // the version string of this chugin, e.g., "v1.2.1"
    QUERY->setinfo( QUERY, CHUGIN_INFO_CHUGIN_VERSION, "" );
    // the author(s) of this chugin, e.g., "Alice Baker & Carl Donut"
    QUERY->setinfo( QUERY, CHUGIN_INFO_AUTHORS, "" );
    // text description of this chugin; what is it? what does it do? who is it for?
    QUERY->setinfo( QUERY, CHUGIN_INFO_DESCRIPTION, "" );
    // (optional) URL of the homepage for this chugin
    QUERY->setinfo( QUERY, CHUGIN_INFO_URL, "" );
    // (optional) contact email
    QUERY->setinfo( QUERY, CHUGIN_INFO_EMAIL, "" );
}


//-----------------------------------------------------------------------------
// query function: ChucK calls this when loading the chugin
// modify this function to define this chugin's API and language extensions
//-----------------------------------------------------------------------------
CK_DLL_QUERY( AmbiCorder )
{
    // generally, don't change this...
    QUERY->setname( QUERY, "AmbiCorder" );

    // ------------------------------------------------------------------------
    // begin class definition(s); will be compiled, verified,
    // and added to the chuck host type system for use
    // ------------------------------------------------------------------------
    // NOTE to create a non-UGen class, change the second argument
    // to extend a different ChucK class (e.g., "Object")

    // 1st order
    QUERY->begin_class( QUERY, "AmbiCorder1", "UGen" );

    // register default constructor
    QUERY->add_ctor( QUERY, ambicorder1_ctor );
    QUERY->add_dtor( QUERY, ambicorder1_dtor );
    QUERY->add_ugen_funcf (QUERY, ambicorder1_tick, NULL, 4, 0 );
    QUERY->add_mfun( QUERY, ambicorder1_openFile, "string", "openFile" );
    QUERY->add_arg( QUERY, "string", "filename" );
    QUERY->add_mfun( QUERY, ambicorder1_closeFile, "void", "closeFile" );
    ambicorder1_data_offset = QUERY->add_mvar( QUERY, "int", "@ac1_data", false );
    QUERY->end_class( QUERY );

    // 2nd order
    QUERY->begin_class(QUERY, "AmbiCorder2", "UGen");

    // register default constructor
    QUERY->add_ctor(QUERY, ambicorder2_ctor);
    QUERY->add_dtor(QUERY, ambicorder2_dtor);
    QUERY->add_ugen_funcf(QUERY, ambicorder1_tick, NULL, 9, 0);
    ambicorder2_data_offset = QUERY->add_mvar(QUERY, "int", "@ac2_data", false);
    QUERY->end_class(QUERY);

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the default constructor
CK_DLL_CTOR( ambicorder1_ctor )
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT( SELF, ambicorder1_data_offset ) = 0;
    
    // instantiate our internal c++ class representation
    AmbiCorder1 * ac_obj = new AmbiCorder1( API->vm->srate(VM) );
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT( SELF, ambicorder1_data_offset ) = (t_CKINT)ac_obj;
}


// implementation for the destructor
CK_DLL_DTOR( ambicorder1_dtor )
{
    // get our c++ class pointer
    AmbiCorder1 * ac_obj = (AmbiCorder1 *)OBJ_MEMBER_INT( SELF, ambicorder1_data_offset );
    // clean up (this macro tests for NULL, deletes, and zeros out the variable)
    CK_SAFE_DELETE( ac_obj );
    // set the data field to 0
    OBJ_MEMBER_INT( SELF, ambicorder1_data_offset ) = 0;
}


// implementation for tick function (relevant only for UGens)
CK_DLL_TICKF( ambicorder1_tick )
{
    // get our c++ class pointer
    AmbiCorder1 * ac_obj = (AmbiCorder1 *)OBJ_MEMBER_INT(SELF, ambicorder1_data_offset);
 
    // invoke our tick function;
    if( ac_obj ) ac_obj->tick( in, out, nframes );

    // yes
    return TRUE;
}


// example implementation for setter
CK_DLL_MFUN( ambicorder1_openFile )
{
    // get our c++ class pointer
    AmbiCorder1 * ac_obj = (AmbiCorder *)OBJ_MEMBER_INT( SELF, ambicorder_data_offset );

    // get next argument
    // NOTE argument type must match what is specified above in CK_DLL_QUERY
    // NOTE this advances the ARGS pointer, so save in variable for re-use
    t_CKFLOAT arg1 = GET_NEXT_FLOAT( ARGS );
    
    // call setParam() and set the return value
    RETURN->v_float = ac_obj->setParam( arg1 );
}


// example implementation for getter
CK_DLL_MFUN( ambicorder1_closeFile )
{
    // get our c++ class pointer
    AmbiCorder1 * ac_obj = (AmbiCorder *)OBJ_MEMBER_INT( SELF, ambicorder_data_offset );

    // call getParam() and set the return value
    RETURN->v_float = ac_obj->getParam();
}
